# Generated by Django 5.1.1 on 2024-10-06 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessment',
            old_name='user',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='tests',
            old_name='user',
            new_name='patient',
        ),
    ]
