# Generated by Django 5.1.1 on 2024-10-06 09:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0003_alter_assessment_patient_alter_tests_patient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assessment',
            new_name='Treatment',
        ),
    ]
