# Generated by Django 5.1.1 on 2024-10-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0009_remove_treatment_assessment_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='treatment_duration',
        ),
        migrations.AlterField(
            model_name='medication',
            name='frequency',
            field=models.CharField(choices=[('Once', 'Once'), ('Twice', 'Twice'), ('Thrice', 'Thrice')], max_length=50),
        ),
        migrations.AlterField(
            model_name='medication',
            name='route_of_administration',
            field=models.CharField(choices=[('Oral', 'Oral'), ('Intravenous', 'Intravenous'), ('Intramuscular', 'Intramuscular'), ('Subcutaneous', 'Subcutaneous'), ('Topical', 'Topical'), ('Inhalation', 'Inhalation'), ('Sublingual', 'Sublingual'), ('Transdermal', 'Transdermal'), ('Nasal', 'Nasal'), ('Ophthalmic', 'Ophthalmic'), ('Otic', 'Otic')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tests',
            name='test_type',
            field=models.TextField(choices=[('Blood Test', 'Blood Test'), ('Urinalysis', 'Urinalysis'), ('Imaging', 'Imaging'), ('Biopsy', 'Biopsy'), ('Genetic Test', 'Genetic Test'), ('Culture', 'Culture'), ('Function Test', 'Function Test'), ('Electrocardiogram', 'Electrocardiogram (ECG)'), ('X-Ray', 'X-Ray'), ('CT-Scan', 'CT-Scan'), ('MRI', 'MRI'), ('Ultrasound', 'Ultrasound'), ('Other', 'Other')], max_length=255),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='treatment_type',
            field=models.CharField(choices=[('Initial Assessment', 'Initial Assessment'), ('Follow Up', 'Follow Up'), ('Therapy', 'Therapy'), ('Surgery', 'Surgery'), ('Medication', 'Medication'), ('Rehabilitation', 'Rehabilitation'), ('Diagnostic', 'Diagnostic'), ('Preventive', 'Preventive'), ('Consultation', 'Consultation')], default='Oral', max_length=50),
        ),
    ]
