# Generated by Django 5.1.1 on 2024-11-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0011_alter_tests_doctor_alter_treatment_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], max_length=50),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='treatment_type',
            field=models.CharField(choices=[('Initial Assessment', 'Initial Assessment'), ('Follow Up', 'Follow Up'), ('Therapy', 'Therapy'), ('Surgery', 'Surgery'), ('Medication', 'Medication'), ('Rehabilitation', 'Rehabilitation'), ('Diagnostic', 'Diagnostic'), ('Preventive', 'Preventive'), ('Consultation', 'Consultation')], max_length=50),
        ),
    ]
