# Generated by Django 5.1.1 on 2024-11-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0012_alter_treatment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='medications',
            field=models.ManyToManyField(blank=True, related_name='medicine', to='medical.medication'),
        ),
    ]
