# Generated by Django 5.1.1 on 2024-12-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0015_remove_treatment_medications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='route_of_administration',
        ),
        migrations.AlterField(
            model_name='treatmentmedication',
            name='frequency',
            field=models.CharField(choices=[('Once', 'Once'), ('Twice', 'Twice'), ('Thrice', 'Thrice')], max_length=50),
        ),
        migrations.AlterField(
            model_name='treatmentmedication',
            name='method_of_administration',
            field=models.CharField(choices=[('Oral', 'Oral'), ('Intravenous', 'Intravenous'), ('Intramuscular', 'Intramuscular'), ('Subcutaneous', 'Subcutaneous'), ('Topical', 'Topical'), ('Inhalation', 'Inhalation'), ('Sublingual', 'Sublingual'), ('Transdermal', 'Transdermal'), ('Nasal', 'Nasal'), ('Ophthalmic', 'Ophthalmic'), ('Otic', 'Otic')], max_length=255),
        ),
    ]
