# Generated by Django 5.0.4 on 2025-02-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_dob_alter_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='changed_password',
            field=models.BooleanField(default=False),
        ),
    ]
