# Generated by Django 5.1.1 on 2024-10-21 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0002_remove_approval_title_approval_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'role': 'Doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='approval',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'role': 'Patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='approval',
            constraint=models.UniqueConstraint(fields=('patient', 'doctor'), name='unique_patient_doctor'),
        ),
    ]
