# Generated by Django 5.1.1 on 2024-10-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0003_alter_approval_doctor_alter_approval_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
