# Generated by Django 5.1.1 on 2024-11-17 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0005_alter_approval_doctor_alter_approval_patient'),
        ('approval', '0006_alter_approval_doctor'),
    ]

    operations = [
    ]
